require("plugins.packer")

require("plugins.cmp")
require("plugins.dap")
require("plugins.formatter")
require("plugins.lualine")
require("plugins.mason")
require("plugins.nvim_tree")
require("plugins.persisted")
require("plugins.smear_cursor")
require("plugins.telescope")
require("plugins.treesitter")
